<a href="https://colab.research.google.com/github/SHAZAN01/Machine-Learning/blob/main/Farm_Yields.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Equation System**

### You will work with a simple data set that contains farm yield values of certain food grains

you will perform the following tasks:
- Load and study the data
- Understand the problem
- Extract yield values as a matrix from the data
- Calculate the number of acres to provide to each farmer to achieve the target yield

### Task 1 - Load and study the data

#### Load the data and study its features such as:
- The number of farmers
- The number of food grain types
- The ranges of yield values

#### Feature Description:

- This data set contains the yearly yield values of rice, wheat, corn and millets per acre promised by four farmers.

- Farmer = name of the farmer
- Rice = amount of rice promised by the farmer in quintals per acre per year
- Wheat = amount of wheat promised by the farmer in quintals per acre per year
- Corn = amount of corn promised by the farmer in quintals per acre per year
- Millets = amount of millets promised by the farmer in quintals per acre per year

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Farm_Yields.csv',index_col='Farmer')
df

Rice  Wheat  Corn  Millets
Farmer                             
Ravi       22     20    37       13
Saju       18     21    43       15
Kishore    17     14    25       28
Satish     12     16    52        8

### Task 2 - Understand the problem


#### Problem Statement

 Assume that the locality served by the four farmers needs the following amounts of food grains in the coming year:
- 373 quintals of rice
- 394 quintals of wheat
- 922 qunitals of corn
- 299 quintals of millets

#### The farm land owner has to decided how many acres to provide to each farmer to achieve this target for his locality

- The data contains the yield values of 4 food grains promised by 4 farmers. These yield values are in quintals per acre per year

#### **Concept and Logic**
1. Let A be matrix of the yield values (4 x 4 matrix)
2. Let X be the number of acres to be provided to each farmer (4 x 1 matrix)
3. Let B be the total required yield values after one year (4 x 1 matrix)
4.  The matrix equation will be A * X = B
5. So, we can solve for X using the equation X = inverse(A) * B

**Note:** The data has farmer names as rows and food grains as columns. For the matrix equation to be meaningful, the matrix A must have farmer names as columns and food grains as rows

![](https://bytepawn.com/images/axb.PNG)

In [ ]:
# 373 quintals of rice
# 394 quintals of wheat
# 922 qunitals of corn
# 299 quintals of millets
B = np.matrix([373,394,922,299]).T
B

matrix([[373],
        [394],
        [922],
        [299]])

In [ ]:
A = df.T
A

Farmer   Ravi  Saju  Kishore  Satish
Rice       22    18       17      12
Wheat      20    21       14      16
Corn       37    43       25      52
Millets    13    15       28       8

### Task 3 - Extract yield values as a matrix from the data

- The farm yield values are in quintals per acre per year
- These yield values will form a 4 x 4 matrix (considering all farmers)

In [ ]:
A = np.matrix(A)
A

matrix([[22, 18, 17, 12],
        [20, 21, 14, 16],
        [37, 43, 25, 52],
        [13, 15, 28,  8]])

### Task 4 - Calculate the number of acres to provide to each farmer to achieve the target yield

##### The farm yield values for rice, wheat, corn and millets for the 4 farmers is a 4 x 4 matrix. The columns hold the yield values of particular farmers. The locality served by the four farmers needs the following amounts of food grains in the coming year:
- 373 quintals of rice
- 394 quintals of wheat
- 922 qunitals of corn
- 299 quintals of millets

1. To find the number of acres to be given to each farmer, we will use systems of linear equations
2. Let "X" be the vector of number of acres to be given to each farmer
3. Then, the required matrix equation will be "mat_yields * X = mat_food"
4. Notice that "mat_yields" is a 4 x 4 matrix and mat_food is a 4 x 1 matrix
5. Hence, "X" will be a 4 x 1 matrix which holds the required number of acres to be given to each farmer
6. So, we can rewrite the equation as "X = inverse of mat_yields * mat_food"

![](https://i.ytimg.com/vi/aiBgjz5xbyg/maxresdefault.jpg)

### **Matrix * Vector**

![](https://hadrienj.github.io/assets/images/2.2/dot-product.png)

In [ ]:
# Hint: "np.linalg.inv()"
X = np.linalg.inv(A)*B
X

matrix([[7.],
        [4.],
        [3.],
        [8.]])

In [ ]:
data = (np.array(X).T)[0]
data

array([7., 4., 3., 8.])

In [ ]:
pd.Series(data,index=df.index)

Farmer
Ravi       7.0
Saju       4.0
Kishore    3.0
Satish     8.0
dtype: float64

In [ ]:
A

matrix([[22, 18, 17, 12],
        [20, 21, 14, 16],
        [37, 43, 25, 52],
        [13, 15, 28,  8]])

In [ ]:
X

matrix([[7.],
        [4.],
        [3.],
        [8.]])

In [ ]:
B

matrix([[373],
        [394],
        [922],
        [299]])

In [ ]:
A*X

matrix([[373.],
        [394.],
        [922.],
        [299.]])

#### Observations

- The farmer Ravi will get 7 acres of land
- The farmer Saju will get 4 acres of land
- The farmer Kishore will get 3 acres of land
- The farmer Satish will get 8 acres of land

### Conclusions

- From the farm yields data and some target yield, we can calculate the distbution of land between farmers
- We can treat the farm yield values of all the farmers as a matrix
- We can use matrix equations and matrix inverses to solve such problems